/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VanityCasesRouteImport } from './routes/vanity-cases'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartenariatsRouteImport } from './routes/partenariats'
import { Route as LizardRouteImport } from './routes/lizard'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const VanityCasesRoute = VanityCasesRouteImport.update({
  id: '/vanity-cases',
  path: '/vanity-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenariatsRoute = PartenariatsRouteImport.update({
  id: '/partenariats',
  path: '/partenariats',
  getParentRoute: () => rootRouteImport,
} as any)
const LizardRoute = LizardRouteImport.update({
  id: '/lizard',
  path: '/lizard',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/lizard': typeof LizardRoute
  '/partenariats': typeof PartenariatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vanity-cases': typeof VanityCasesRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/lizard': typeof LizardRoute
  '/partenariats': typeof PartenariatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vanity-cases': typeof VanityCasesRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/lizard': typeof LizardRoute
  '/partenariats': typeof PartenariatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vanity-cases': typeof VanityCasesRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collection'
    | '/lizard'
    | '/partenariats'
    | '/sitemap.xml'
    | '/vanity-cases'
    | '/product/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collection'
    | '/lizard'
    | '/partenariats'
    | '/sitemap.xml'
    | '/vanity-cases'
    | '/product/$handle'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collection'
    | '/lizard'
    | '/partenariats'
    | '/sitemap.xml'
    | '/vanity-cases'
    | '/product/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionRoute: typeof CollectionRoute
  LizardRoute: typeof LizardRoute
  PartenariatsRoute: typeof PartenariatsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VanityCasesRoute: typeof VanityCasesRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vanity-cases': {
      id: '/vanity-cases'
      path: '/vanity-cases'
      fullPath: '/vanity-cases'
      preLoaderRoute: typeof VanityCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenariats': {
      id: '/partenariats'
      path: '/partenariats'
      fullPath: '/partenariats'
      preLoaderRoute: typeof PartenariatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lizard': {
      id: '/lizard'
      path: '/lizard'
      fullPath: '/lizard'
      preLoaderRoute: typeof LizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionRoute: CollectionRoute,
  LizardRoute: LizardRoute,
  PartenariatsRoute: PartenariatsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VanityCasesRoute: VanityCasesRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
